---
- name: Create a temporary directory for building the container image
  register: temp_file
  tempfile:
    path: /tmp
    state: directory
    prefix: hadockerbuild-

- name: Copy files to the remote temporary directory
  copy:
    src: '{{ role_path }}/files/{{ item }}'
    dest: '{{ temp_file.path }}'
  loop:
    - Dockerfile
    - haproxy.cfg
    - docker-entrypoint.sh
    - rsyslog.conf

- name: Copy the encrypted certificate file
  copy:
    src: '{{ role_path }}/files/dschallenge.pem.vault'
    dest: '{{ temp_file.path }}/dschallenge.pem'
    decrypt: yes

- name: Build the haproxy docker image
  docker_image:
    path: '{{ temp_file.path }}'
    name: '{{ ha_image_name }}'
    repository: '{{ docker_registry }}/{{ ha_image_name }}:latest'
    push: yes
    state: present
    nocache: yes
    force: yes

- name: Remove the temporary build directory
  file:
    path: '{{ temp_file.path }}'
    state: absent
