---
- name: Run the haproxy container
  docker_container:
    name: '{{ ha_container_name }}'
    image: '{{ docker_registry}}/{{ ha_image_name }}:latest'
    state: started
    recreate: yes
    ports:
      - 80:80
      - 443:443
    networks:
      - name: '{{ docker_internal_network }}'
