---
- name: Enable rsyslog to forward logs to Graylog
  copy:
    src: '{{ role_path }}/files/rsyslog-graylog.conf'
    dest: /etc/rsyslog.d/50-rsyslog-graylog.conf
  notify:
    - restart rsyslog

- name: Install Node Exporter for Prometheus
  apt: name=prometheus-node-exporter state=present

- name: Ensure the service above is enabled and running
  systemd: name=prometheus-node-exporter state=restarted enabled=yes
