---
- name: Create a temporary directory for building the container image
  register: temp_file
  tempfile:
    path: /tmp
    state: directory
    prefix: dockerbuild-

- name: Copy the Dockerfile to the remote temporary directory
  copy:
    src: '{{ role_path }}/files/Dockerfile'
    dest: '{{ temp_file.path }}'

- name: Build the application docker image
  docker_image:
    path: '{{ temp_file.path }}'
    name: '{{ app_container_name }}'
    repository: '{{ docker_registry }}/{{ app_container_name }}:latest'
    push: yes
    state: present
    nocache: yes
    buildargs:
      APP_DATABASE_USER: '{{ db_user }}'
      APP_DATABASE_PASSWORD: '{{ db_password }}'
      APP_DATABASE_URL: "jdbc:postgresql://{{ db_container_name }}:{{ db_port }}/{{ db_name }}"
      APP_DATABASE_SCHEMA: "none"

- name: Remove the temporary build directory
  file:
    path: '{{ temp_file.path }}'
    state: absent
