---
- name: Run the application container
  docker_container:
    name: '{{ app_container_name }}'
    image: '{{ docker_registry}}/{{ app_container_name }}:latest'
    state: started
    networks:
      - name: '{{ docker_internal_network }}'
    ports:
      - 8080:8080
    env:
      APP_DATABASE_USER: '{{ db_user }}'
      APP_DATABASE_PASSWORD: '{{ db_password }}'
      APP_DATABASE_URL: "jdbc:postgresql://{{ db_container_name }}:{{ db_port }}/{{ db_name }}"
