---
- name: Run the application container
  docker_container:
    name: '{{ app_container_name }}'
    image: '{{ docker_registry}}/{{ app_container_name }}:latest'
    state: started
    networks:
      - name: '{{ docker_internal_network }}'
    ports:
      - 8080:8080
    env:
      APP_DATABASE_USER: "entries"
      APP_DATABASE_PASSWORD: "entries"
      APP_DATABASE_URL: "jdbc:postgresql://db:5432/entries"
      APP_DATABASE_SCHEMA: "create"
