---
- name: Create a temporary directory for building the container image
  register: temp_file
  tempfile:
    path: /tmp
    state: directory
    prefix: dockerbuild-

- name: Copy the Dockerfile to the remote temporary directory
  copy:
    src: '{{ role_path }}/files/Dockerfile'
    dest: '{{ temp_file.path }}'

- name: Build the application docker image
  docker_image:
    path: '{{ temp_file.path }}'
    name: demo-app

- name: Remove the temporary build directory
  file:
    path: '{{ temp_file.path }}'
    state: absent
