---
- name: Create a temporary directory for building the container image
  register: temp_file
  tempfile:
    path: /tmp
    state: directory
    prefix: promdockerbuild-

- name: Copy the Dockerfile to the remote temporary directory
  copy:
    src: '{{ role_path }}/files/{{ item }}'
    dest: '{{ temp_file.path }}'
  loop:
    - Dockerfile

- name: Copy the prometheus.yml template
  template:
    src: prometheus.yml
    dest: '{{ temp_file.path }}/prometheus.yml'

- name: Build the Prometheus docker image
  docker_image:
    path: '{{ temp_file.path }}'
    name: prometheus
    repository: '{{ docker_registry }}/prometheus:latest'
    push: yes
    state: present
    nocache: yes
    force: yes

- name: Remove the temporary build directory
  file:
    path: '{{ temp_file.path }}'
