---
- name: sysctl entry required for elasticsearch: vm.max_map_count=262144
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: yes

- name: Run elastic container
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    state: started
    recreate: yes
    networks:
      - name: '{{ docker_internal_network }}'
    env:
      http.host: "0.0.0.0"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
